### ISSUE TITLE
Designer doesn't compile with .NET Native (RHB0002)

### ISSUE THREAD

**Issue by MattWhilden** [SuperJMN/SuppaDesigner#3]
This is a follow up to [this twitter thread](https://twitter.com/SuperJMN/status/1205637000709234693?s=20). I've also provided some reading/suggestions in [this gist](https://gist.github.com/MattWhilden/3bf112d7cdf5507cd604f1363550d7c7). I figure this is a better text box than 280 characters at a time on twitter. 😊

I have some other tasks today that will keep me from digging in too much but maybe you can get lucky a bit given the notes below. Certainly let me know!

**The Issue**
The short answer is that the particular arrangement of libraries has caused .NET Native to lose it's mind and we'll need to write some hints about what types/members/namespaces can be safely ignored. Fortunately, the compiler is very generous about writing out artifacts at various stages that should make our lives easier. I'll dive into one in particular that should help us out.

The gist above describes "start with everything" and a "Start with nothing" approach. Given how things are interconnects I suspect it'll be better to "Start with everything". But how do you know where to start? 

**Reflection Log**
After a build (even most failed ones), the compiler will generate a ton of information in obj\ARCHITECTURE\Release\ilc\. The "In" folder is everything passed to the compiler at the start. The Intermediates are artifacts the compiler spits out as it move through various phases. 

Analysis is one of the earliest phases and any algorithm running away there will cause huge issues downstream. It's the first place I like to check. The artifacts from analysis end up in the Intermediates\ILTransformed directory. You'll have .ildll and .ilpbd files which are your app binaries twiddled a bit to make them a bit more .NET Native friendly but more importantly you'll have a collection of .csv files:
- A closure file containing a list of all the dlls your app references
- <appname>.csv with pdb and assembly info
- A file to track all forwarded types
- A file showing the result of all the decisions about which types need to be saved/generated etc due to reflection analysis

The last file is the one we're after. It'll be named Designer.reflectionlog.csv. 

**Example Analysis**
I was tracking down a similar issue where the latest versions of System.Reactive. Here's the reflogs for a couple of different compilations:
<img width="289" alt="reflogRX" src="https://user-images.githubusercontent.com/9834438/71203489-e7369c80-2252-11ea-900d-4db8996dfe91.PNG">

It immediately jumps out that something has changed in 4.3. Running a diff on the logs shows a TON of entries for generics using the System.Reactive.Concurrency namespace. The "big hammer" here would be to write a directive like:
`<Namespace Name="System.Reactive.Concurrency" Dynamic="Excluded" />`
I suspect this is a bit heavy handed and will lead to issues when the app is run but those one offs may be easier to chase down. If not, the next step would be to go look directly at System.Reactive.Concurrency and find a subset of things to disable.

**Designer**
The "good" news is that Designer seems to be suffering from the same issue. The reflog for designer isn't a few hundred megs... My build has it at a quite impressive 2.5 GIGS! It's also filled with a huge amount of  System.Reactive.Concurrency elements and seems completely unreasonable.

**Comment by MattWhilden** [comment]
Just for the sake of playing around and getting it to compile I've added this directive:
`<Assembly Name="System.Reactive" Dynamic="Excluded"/>`
This lets it get through the compiler (and reduces the reflog to a more managable 100MB) and back to the other issue in the twitter thread. 

That first chance exception seems [expected](https://github.com/ExtendedXmlSerializer/home/blob/b8566a7f1a9cfb3795d48e4ef268fc3986207c19/src/ExtendedXmlSerializer/ExtensionModel/Xml/DefaultMemberOrder.cs#L41). There's a bunch of those and then a series of FileNotFoundExceptions looking for ReactiveUI.XamForms.dll and kin.

Finally, a MissingMetadataException that tears down the process. If you run in DEBUG but with .NET Native enabled (Project properties > Build > Enable .NET Native) you can start working through adding back the things that have been stripped away but are still necessary. It should end up looking like this:
<img width="303" alt="MME" src="https://user-images.githubusercontent.com/9834438/71216178-ac426200-226e-11ea-961e-6e7a9cbc2b98.PNG">

We have [a troubleshooter](https://dotnet.github.io/native/troubleshooter/type.html) that can help with syntax. You can add this back to the compilation with another directive like so:
`<Type Name="Windows.Foundation.IReference{Double}" Dynamic="Required All" />`

Going back in to the next loop to see what happens but will have to head home here in a bit.

**Comment by MattWhilden** [comment]
Ah, that's actually a super interesting type. I don't think the source is in one of our public repos but it's marks as NonReflectable. ILSpy or ILDasm will show it decorated with:
`[System.Runtime.CompilerServices.__BlockReflection]`

Hmmm. So this won't ever work and we'll need to chase down which chunk of code sent us down this path.

**Comment by MattWhilden** [comment]
Alright before I bail I'll just note that before we head into this path, the XAML subsystem is chewing through MainSurfaceControl, winding through some brush options and then calling back into C# land asking about `Windows.Foundation.IReference<Double>`. It's possible swizzling things around a bit can get things unjammed.

**Comment by SuperJMN** [comment]
Oh my... I'm quite lost it seems.
For what I understand, reflection heavy tasks are tricky for the .NET Native Compiler.

For what I know, these libs are using Reflection extensively:
- Refit
- Grace
- ExtendedXMLSerializer

Do you think the issue is on their side (because they are using reflection in a 'bad way'? or because the compiler doesn't handle complex reflection scenarios reasonably?

**Comment by MattWhilden** [comment]
I haven't had a ton of time to chew on this but feel compelled to post an update anyway.

One of the compiler issues is addressed in RX by [this commit](https://github.com/dotnet/reactive/commit/3cebafab4653068e35e2b82528ee625de049f22e). we're still stuck at the MissingMetadataException for the special IReference type but that will require some more know how.

Once folks return from holiday I should have more time to poke around... when you're the last man in the building you get stretched a bit thin 😊

**Comment by MagicAndre1981** [comment]
> Finally, a MissingMetadataException that tears down the process. If you run in DEBUG but with .NET Native enabled (Project properties > Build > Enable .NET Native) you can start working through adding back the things that have been stripped away but are still necessary. It should end up looking like this:
> <img alt="MME" width="303" src="https://user-images.githubusercontent.com/9834438/71216178-ac426200-226e-11ea-961e-6e7a9cbc2b98.PNG">
> 
> We have [a troubleshooter](https://dotnet.github.io/native/troubleshooter/type.html) that can help with syntax. You can add this back to the compilation with another directive like so:
> `<Type Name="Windows.Foundation.IReference{Double}" Dynamic="Required All" />`
> 
> Going back in to the next loop to see what happens but will have to head home here in a bit.

offtopic, but I also get this when using SfDataGrid in my xamarin app in ARM64 mode (remote debug on Win10 Pro 1909 ARM64), here this .net native thing is also used for debug mode. I've added the entry to my app, but still crashes with same error in XamlTypeInfo.g.cs.

![image](https://user-images.githubusercontent.com/8274816/73434470-1870b500-4347-11ea-9372-d78360aeac7a.png)

@MattWhilden please add an entry to disable the optimization like in Xamarin Android (don't link). For sideloading app size is not an issue.
